# Generated by Django 4.2.7 on 2025-11-22 05:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0013_category_is_active_category_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="Size",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Nome do Tamanho"
                    ),
                ),
                (
                    "abbreviation",
                    models.CharField(
                        help_text="Ex: P, M, G, GG",
                        max_length=10,
                        verbose_name="Abreviação",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordem de Exibição"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Tamanho",
                "verbose_name_plural": "Tamanhos",
                "ordering": ["order", "name"],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="sizes",
            field=models.ManyToManyField(
                blank=True, to="products.size", verbose_name="Tamanhos Disponíveis"
            ),
        ),
    ]
