# Generated by Django 4.2.7 on 2025-11-22 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0014_size_product_sizes"),
        ("cart", "0016_alter_orderitem_options_orderitem_color_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="cartitem",
            name="unique_cart_product_color",
        ),
        migrations.AddField(
            model_name="cartitem",
            name="size",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.size",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="size",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.size",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="size_abbreviation",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="size_name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.UniqueConstraint(
                fields=("cart", "product", "color", "size"),
                name="unique_cart_product_color_size",
            ),
        ),
    ]
