# Generated by Django 4.2.7 on 2025-11-06 22:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0004_customerprofile_postal_code"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomerAddress",
        ),
    ]
