# Generated by Django 4.2.7 on 2025-11-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0005_delete_customeraddress"),
    ]

    operations = [
        migrations.AddField(
            model_name="externalauthuser",
            name="admin_source",
            field=models.CharField(
                blank=True,
                choices=[("email", "Email Config"), ("manual", "Manual Promotion")],
                help_text="Source of admin privilege: 'email' (from FIREBASE_ADMIN_EMAILS) or 'manual' (promoted via UserManagement)",
                max_length=20,
                null=True,
            ),
        ),
    ]
